spring:
  application:
    name: ordem-servico

  datasource:
    url: jdbc:mysql://localhost:3306/senai_os?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true